GET http://localhost:5022

### Get all Books
GET http://localhost:5022/books?searchByTitle=code&searchByAuthor=Martin

### Get One Book with ID
GET http://localhost:5022/books/3

### Create New Book
POST http://localhost:5022/books/store
Content-Type: application/json

{
    "title": "The title",
    "author": "author",
    "genre" : "Advanture"
}

### Update Book
PUT http://localhost:5022/books/update
Content-Type: application/json

{
    "id": 3,
    "title": "The Monke",
    "author": "Adu",
    "genre" : "Advanture"
}

### Delete Book
DELETE http://localhost:5022/books/delete
Content-Type: application/json

{
    "id": 4
}
